{% set version = "1.0.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-anylib
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/anyLib_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/anyLib/anyLib_{{ version }}.tar.gz
  sha256: 759b53ecc58136458220108a72004f360404ad2769cbf6ead48dcf09212a3df5

build:
  merge_build_host: true  # [win]
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-biocmanager
    - r-curl
    - r-devtools
    - r-httr
    - r-withr
  run:
    - r-base
    - r-biocmanager
    - r-curl
    - r-devtools
    - r-httr
    - r-withr

test:
  commands:
    - $R -e "library('anyLib')"           # [not win]
    - "\"%R%\" -e \"library('anyLib')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=anyLib
  license: CC-BY-SA-4.0
  summary: Made to make your life simpler with packages, by installing and loading a list of packages, whether they are on CRAN, Bioconductor or github. For github, if you do not have the full path, with the maintainer name in it (e.g. "achateigner/topReviGO"), it will be able to load it but not to install it.
  license_family: CC
  license_file:
    - LICENSE-CC-BY-SA-4

extra:
  recipe-maintainers:
    - conda-forge/r
